### PR TITLE
Allow testing of Webhooks using ENV

### PR DESCRIPTION
**Pull request by phleobon**
After seeing the pull request #190 I wanted to contribute with what looks to me a better solution.

As @taylorotwell said using environment variables looked like a better choice.

To keep it simple I added a isInTestingMode method that return a boolean according to the CASHIER_TESTING env variable.

Then in the handleWebhook method we can verify that we are not in testing mode.

### CODE REVIEW

**Comment by phleobon** [comment]
Well, I don't really understand what is the problem with StyleCI.
So I am going to start over.

**Comment by GrahamCampbell** [comment]
You had trailing whitespace. You could have just downloaded the diff it gave you and applied it instead of manually trying to fix it though...

**Comment by phleobon** [comment]
I am not used to github stuff yet. 

I'll try that then.

**Comment by GrahamCampbell** [comment]
Please squash to one commit.

**Comment by GrahamCampbell** [comment]
(and force push)

**Comment by phleobon** [comment]
I might have done something wrong..

Sorry for my poor git knowledge

**Comment by phleobon** [comment]
I will close this and start over.

**Pull request closed without merging**
