### PR TITLE
Added @subscribed blade directive

### PR DESCRIPTION
**Pull request by yamenarahman**
#479

### CODE REVIEW

**Comment by taylorotwell** [comment]
Things like this would typically go in the `boot` method.

**Comment by yamenarahman** [comment]
@taylorotwell That's what I did, I just thought to make it go in the `CachierServiceProvider` and open the door for any other blade extensions there.

**Comment by taylorotwell** [comment]
It's not in the boot method.

**Comment by yamenarahman** [comment]
The changes on the `Billable` trait are auto PSR2 fixes.

**Comment by yamenarahman** [comment]
If this PR will be merged should I update the docs ?

**Comment by taylorotwell** [comment]
This has some problems. First, `plan` is not the first argument of subscribed, secondly it would need to match the subscribed signature entirely so that it provides the same functionality.

**Pull request closed without merging**
