### PR TITLE
Fixed onTrial Method

### PR DESCRIPTION
**Pull request by mobelio**
Argument 1 passed to Carbon\Carbon::lt() must be an instance of Carbon\Carbon

### CODE REVIEW

**Comment by taylorotwell** [comment]
Fix tests?

**Comment by mobelio** [comment]
Why tests? 
src/Laravel/Cashier/Billable.php

**Comment by GrahamCampbell** [comment]
@mobelio You broke our unit tests, so you must adjust them, or fix your implementation to pass.

**Comment by mobelio** [comment]
@GrahamCampbell, @taylorotwell oh sorry, just make it at monday =)

**Pull request closed without merging**
