### PR TITLE
[10.x] Retrieve payment method

### PR DESCRIPTION
**Pull request by geoffs3310**
I've added a method to retrieve a payment method from Stripe by its ID in order to verify that a token is valid. Since the token is generated on the front end it can be manipulated and so I needed a way to validate it in a form request before I attempt to attach it to the customer.

### CODE REVIEW

**Comment by driesvints** [comment]
I don't see the need for this tbh. Just use the PaymentMethod::retrieve from Stripe.

**Comment by geoffs3310** [comment]
That's true of other methods in the Billable trait such as findInvoice but that made it in?

**Comment by geoffs3310** [comment]
Plus you're already doing the call anyway in resolveStripePaymentMethod but because its protected it's no use to anyone. So I suggest either making that method public or merging this PR in.

**Comment by driesvints** [comment]
@geoffs3310 hmm yeah I see your point. Let's try making the existing method public instead.

**Comment by driesvints** [comment]
@geoffs3310 I'll send in a new PR for this in a bit.

**Comment by driesvints** [comment]
Here: https://github.com/laravel/cashier/pull/801

**Pull request closed without merging**
