### PR TITLE
Add relation on a given model, rather than hard-coded relation

### PR DESCRIPTION
**Pull request by nathanjdunn**
Updated from #264

### CODE REVIEW

**Comment by taylorotwell** [comment]
Just curious what is the name of your model that has subscriptions if its not user?

**Comment by nathanjdunn** [comment]
I'm currently developing a single database multi-tenant system which an `Account` model that all of my users belong to.

**Comment by taylorotwell** [comment]
Going to hold off on this for now.

**Comment by NicolasPK** [comment]
Such a shame this got closed but #337 got merged, as this fix is working for laravel 5.1 lts whereas the 7.0 branch is not.

**Pull request closed without merging**
