### PR TITLE
[6.0] Add PHPCS

### PR DESCRIPTION
**Pull request by lucasmichot**
Add PHPCS
The same as for laravel/framework

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by lucasmichot** [comment]
Why?

**Comment by GrahamCampbell** [comment]
It is not recommended for contributors to run php-cs-fixer as it's a total waste of their time, and the results aren't exactly the same as styleci anyway.

**Comment by GrahamCampbell** [comment]
StyleCI is setup to merge any fixes after the PR is merged so it doesn't matter if it's failing at review.

**Pull request closed without merging**
