### PR TITLE
Add hasCardOnFile method to Billable

### PR DESCRIPTION
**Pull request by Francismori7**
Allows you to check if the customer currently has a card on file.

I couldn't get tests to run on my system.

### CODE REVIEW

**Comment by Francismori7** [comment]
Allows you to check if the customer currently has a card on file. I couldn't get tests to run on my system.

Do not merge yet. Some issues happened on my end.

**Comment by taylorotwell** [comment]
What situations have you had where the local database doesn't have the card information but Stripe does have card information?

**Comment by Francismori7** [comment]
While testing I would add the card in stripe and it wouldn't follow too good and caused issues. 

I was just checking card brand in the user data and figured a fallback option would be nice.

Again do not merge there's an issue with default source

**Comment by taylorotwell** [comment]
OK make another PR when your'e ready.

**Comment by Francismori7** [comment]
Will do tonight or something like that, got it fixed in my codebase alreary

**Pull request closed without merging**
