### PR TITLE
[10.x] Refactor handling of invalid webhook signatures

### PR DESCRIPTION
**Pull request by sebdesign**
We can rid of the `\Illuminate\Contracts\Foundation\Application` dependency in the `VerifyWebhookSignature` constructor, by manually throwing a 403 exception.

This simplifies both the implementation and the tests, and it allows us to pass the message and the original exception to the exception handler.

### CODE REVIEW

**Comment by driesvints** [comment]
On thing on my mind is people extending the class and using the app property but that seems very unlikely tbh.

**Comment by sebdesign** [comment]
Yeah I doubt people would want to extend this middleware. :)

**Comment by sebdesign** [comment]
@driesvints should we remove the config repository dependency as well? We are using `config('cashier...)` everywhere except from this class.

**Comment by driesvints** [comment]
@sebdesign I think that was still needed for the tests but if you can simplify it then go for it.

**Comment by sebdesign** [comment]
@driesvints I'll do it tonight! The goal is to simplify tests as well.

**Pull request merged**
