### PR TITLE
Renamed Billable trait as per guidelines

### LINKED ISSUE #221: Billable doesn't following guidelines
The `Billable` trait should instead be called `BillableTrait` according to the contribution guidelines "Interface and Trait names are suffixed with Interface (FooInterface) and Trait (FooTrait) respectively."

### PR DESCRIPTION
**Pull request by Francismori7**
Fixes #221

### CODE REVIEW

**Comment by taylorotwell** [comment]
Those are terrible guidelines.

**Comment by Francismori7** [comment]
https://github.com/laravel/cashier/blob/6.0/contributing.md#coding-guidelines

**Comment by taylorotwell** [comment]
I will remove that.

**Comment by Francismori7** [comment]
Alright thanks I'll update my branch accordingly

**Pull request closed without merging**
