### PR TITLE
[10.0] Update UPGRADE.md

### PR DESCRIPTION
**Pull request by driesvints**
This updates the upgrade guide for the upcoming v10 release.

### CODE REVIEW

**Comment by garygreen** [comment]
Great work with this @driesvints much appreciated. Just curious, what's the release schedule/plan for v10? I assume the target is for it to be released sometime before the upcoming SCA requirement for Stripe from 14th September? Would be great to get some reassurance it'll be released with a fair amount of time for developers to react and update their implementations.

**Comment by driesvints** [comment]
@garygreen yeah I know we're cutting it a little short, sorry for that. About to do a second beta release (or tomorrow). Would really appreciate any help with testing that.

**Comment by hassanazimi** [comment]
Hi @driesvints I am testing this and everything works, I have tested this with incomplete card however and there is a section in this Upgrade guide:

```
@if ($user->hasIncompletePayment())
    <a href="{{ route('cashier.payment', $user->subscription()->latestPayment()->id) }}">
        Please confirm your payment.
    </a>
@endif
```

I can't seem to find `hasIncompletePayment()` and `latestPayment()` in Billable. Am I missing something?

**Comment by driesvints** [comment]
@hassanazimi are you requiring dev-master? That functionality was added after the first beta release.

**Comment by hassanazimi** [comment]
In that case, everything worked! 🙌🏽

**Comment by damcclean** [comment]
Hey!

Whenever I run `php artisan migrate` after updating an app of mine. It gives me an error because the stripe columns already exist on my users table. It is trying to run the `CreateCustomerColumns` migration from within the Cashier package. How would I get laravel to ignore this migration (as the columns already exist)?

Thanks for the update guide 👍

**Comment by driesvints** [comment]
Hey @damcclean, this is documented in this upgrade guide. Check the "Migrations" section.

**Comment by damcclean** [comment]
> Hey @damcclean, this is documented in this upgrade guide. Check the "Migrations" section.

Ah, sorry for that 🤦‍♂️ I haven't got to that part of the guide yet.

**Comment by driesvints** [comment]
@damcclean that's a good remark actually. I've moved them to the top of the upgrade guide.

**Pull request merged**
