### PR TITLE
Switch path and namespace for loadViewsFrom

### PR DESCRIPTION
**Pull request by DraperStudio**

### CODE REVIEW

**Comment by carnevalle** [comment]
This fixes a bug for me where Laravel can't find the invoice view. The generated PDF however is corrupt, which probably has nothing to do with this fix.

**Comment by DraperStudio** [comment]
@carnevalle If you have issues with corrupted Invoice PDFs this will probably solve your issue.

http://www.sixteenink.com/laravel-cashier-pdf-corrupt/

**Comment by rossedman** [comment]
This solved both of my bugs. I could not generate PDFs and I had permission errors with phantomjs.

**Comment by taylorotwell** [comment]
Fixed.

**Pull request closed without merging**
